# Generated by Django 4.1 on 2022-08-30 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0003_rename_approved_feedback_status_alter_feedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.DateField(auto_now=True)),
                ('semestre', models.IntegerField(choices=[('1º semestre', 'Primeiro'), ('2º semestre', 'Segundo'), ('3º semestre', 'Terceiro'), ('4º semestre', 'Quarto')])),
                ('materia', models.CharField(choices=[('Português', 'Portugues'), ('Geografia', 'Geografia'), ('História', 'Historia'), ('Física', 'Fisica'), ('Matemática', 'Matematica'), ('Ciência', 'Ciencia'), ('Química', 'Quimica')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.semestre')),
            ],
        ),
    ]
