# Generated by Django 4.0.6 on 2022-08-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'student'),
                    (2, 'teacher'),
                    (3, 'parent'),
                    (4, 'admin'),
                ],
                default=1,
            ),
        ),
    ]
