# Generated by Django 4.1 on 2022-08-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_avatar_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='semester',
            new_name='ano_letivo',
        ),
    ]
