on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  heroku_git_deploy_job:
      runs-on: ubuntu-latest
      name: Git Deploy job- A job to deploy django app to heroku using git
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Deploy django to heroku
          uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_app_name : ${{ secrets.HEROKU_APP_RI_NAME }}
            heroku_api_key: ${{ secrets.HEROKU_API_SECRET_KEY }}
            heroku_email: 'gabrieltggv29@gmail.com'
            usedocker: true
            branch: "main"
            stack: "container"
